import type { Metadata } from "next";
import Footer from "@/components/sections/Footer";
import Eyebrow from "@/components/ui/Eyebrow";

export const metadata: Metadata = {
  title: "Privacy — Swipe & Scale",
  description:
    "What Swipe & Scale collects when you use this site, why, and how to have it deleted.",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return (
    <>
      <a
        href="#main"
        className="btn btn-solid sr-only focus:not-sr-only focus:absolute focus:left-[var(--gutter)] focus:top-[var(--gutter)] focus:z-50"
      >
        Skip to content
      </a>

      <main id="main" className="px-[var(--gutter)] py-[var(--stack-lg)]">
        <Eyebrow className="text-bone/70">LEGAL</Eyebrow>
        <h1 className="display mt-[clamp(1rem,2vh,1.75rem)] text-h1 text-bone">Privacy</h1>
        <p className="mono mt-[clamp(1rem,2vh,1.5rem)] text-bone/70">
          LAST UPDATED 1 JANUARY 2026
        </p>

        <div className="prose mt-[var(--stack-md)] flex flex-col gap-[clamp(1.5rem,3vh,2.25rem)] text-body text-bone/80">
          <p>
            Swipe &amp; Scale is a one-person design studio. This site is a marketing page. It
            has no accounts, no login, and no shopping cart, so there is very little to say
            here — but what there is, is said plainly.
          </p>

          <section>
            <h2 className="display text-h3 text-bone">What this site stores on your device</h2>
            <p className="mt-3">
              Nothing. There are no cookies, no analytics scripts, no advertising pixels, and
              nothing is written to your browser&apos;s storage. Closing the tab leaves nothing
              behind.
            </p>
          </section>

          <section>
            <h2 className="display text-h3 text-bone">What happens when you use the form</h2>
            <p className="mt-3">
              The contact form sends the name, email address, company, budget range, and
              message you type to Formspree, which forwards it to my inbox and keeps a copy in
              its dashboard. I use that information for one thing: replying to you about the
              project you described. It is never sold, never used for marketing lists, and
              never shared with anyone outside Formspree and my email provider.
            </p>
          </section>

          <section>
            <h2 className="display text-h3 text-bone">Hosting and server logs</h2>
            <p className="mt-3">
              The site is hosted on Vercel, which keeps short-lived request logs — IP address,
              browser, and requested URL — for security and diagnostics. Those logs are
              Vercel&apos;s, are generated by every request to every site they host, and are
              not used for tracking here.
            </p>
          </section>

          <section>
            <h2 className="display text-h3 text-bone">How long I keep enquiries</h2>
            <p className="mt-3">
              Enquiries that do not turn into projects are deleted within twelve months.
              Project correspondence is kept for as long as the work needs it and for six
              years afterwards, which is what accounting records require.
            </p>
          </section>

          <section>
            <h2 className="display text-h3 text-bone">Getting your data removed</h2>
            <p className="mt-3">
              Email{" "}
              <a href="mailto:hello@swipeandscale.studio" className="text-bone underline">
                hello@swipeandscale.studio
              </a>{" "}
              and ask. I will delete everything I hold about you and confirm it within thirty
              days. You do not need to give a reason.
            </p>
          </section>

          <p>
            If anything on this page is unclear, ask me directly rather than guessing. Same
            address.
          </p>
        </div>
      </main>

      <Footer />
    </>
  );
}
