/**
 * Auth.js (NextAuth v5) configuration. BUILD_SPEC §2: Resend magic link +
 * Google OAuth, no per-MAU cost, self-hosted.
 *
 * Session strategy is "database" (the adapter default) rather than "jwt":
 * with database sessions, suspending a workspace or removing a member can
 * be enforced by deleting rows the next request will look up, instead of
 * waiting out a signed token's lifetime. See DECISIONS §9.
 *
 * This file does not itself enforce tenancy — it only answers "who is
 * this". Every workspace-scoped check happens in `src/server/tenancy.ts`.
 */
import { PrismaAdapter } from "@auth/prisma-adapter";
import NextAuth from "next-auth";
import Google from "next-auth/providers/google";
import Resend from "next-auth/providers/resend";

import { db } from "@/server/db";
import { sendMagicLinkEmail } from "@/server/email";

export const { handlers, auth, signIn, signOut } = NextAuth({
  // `db` is generated by Prisma's newer `prisma-client` generator (custom
  // output path, see prisma/schema.prisma), not the classic `@prisma/client`
  // package the adapter's TS signature names. Both are the same shape at
  // runtime — same Prisma version, same models — and the adapter only reads
  // `prisma.<model>` methods, so this is safe. See DECISIONS §9.
  adapter: PrismaAdapter(db),
  session: { strategy: "database" },
  trustHost: true,
  secret: process.env.AUTH_SECRET,
  providers: [
    Google,
    Resend({
      apiKey: process.env.RESEND_API_KEY,
      from: process.env.AUTH_EMAIL_FROM || undefined,
      // Rate limiting for this flow lives in the caller (the
      // `requestMagicLink` server action), not here — it has the request's
      // IP address from `headers()` without relying on this callback's
      // `request` param, and it can reject before Auth.js ever creates a
      // verification token row.
      async sendVerificationRequest({ identifier, url }) {
        await sendMagicLinkEmail({ to: identifier, url });
      },
    }),
  ],
  pages: {
    signIn: "/login",
    verifyRequest: "/verify",
  },
  callbacks: {
    async session({ session, user }) {
      session.user.id = user.id;
      session.user.isPlatformAdmin = Boolean(
        (user as { isPlatformAdmin?: boolean }).isPlatformAdmin,
      );
      return session;
    },
  },
});
